name: MotivationMediaInc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7001074480358511
title: Motivation Media Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ff0016'
    - '#cfcfcf'
    - '#9f9f9f'
  brandStrength: 0.8481216959189624
  lightness: 0.8931689390446991
  saturation: 0.8830494440626353
  rhythmicContrast: 1
purpose: []
